# Generated by Django 3.2.7 on 2021-09-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='productorder',
            name='customerOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customeroder'),
        ),
    ]
