# Generated by Django 3.2.7 on 2021-09-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210904_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOder',
            new_name='CustomerOrder',
        ),
    ]
