# Generated by Django 3.2.7 on 2021-09-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_customeroder_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='products',
            field=models.ManyToManyField(to='base.Product'),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
