# Generated by Django 3.2.7 on 2021-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customerorder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
