# Generated by Django 3.2.7 on 2021-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customerorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
